export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out forwards',
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
        'fade-in-down': 'fadeInDown 0.6s ease-out forwards',
        'slide-in-up': 'slideInUp 0.5s ease-out forwards',
        'slide-in-left': 'slideInLeft 0.5s ease-out forwards',
        'slide-in-right': 'slideInRight 0.5s ease-out forwards',
        'zoom-in': 'zoomIn 0.5s ease-out forwards',
        'zoom-out': 'zoomOut 0.5s ease-out forwards',
        'scale-in': 'scaleIn 0.4s ease-out forwards',
        'bounce-in': 'bounceIn 0.6s ease-out forwards',
        'chart-entrance': 'chartEntrance 0.8s ease-out forwards',
        'count-up': 'countUp 0.6s ease-out forwards',
        'shimmer': 'shimmer 2s infinite linear',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'pulse-cta': 'subtlePulse 3s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
        'border-glow': 'borderGlow 2s ease-in-out infinite',
        'gradient-shift': 'gradientShift 8s ease infinite',
        'spin-slow': 'spin 3s linear infinite',
        'slide-down': 'slideDown 0.3s ease-out forwards',
        'slide-up': 'slideUp 0.3s ease-out forwards',
        'pop': 'pop 0.3s ease-out forwards',
        'live-pulse': 'livePulse 2s ease-in-out infinite',
        'ripple': 'ripple 0.6s ease-out',
        'shake': 'shake 0.5s ease-in-out',
        'data-flash': 'dataFlash 0.4s ease-out forwards',
        'bar-rise': 'barRise 0.6s ease-out forwards',
        'icon-bounce': 'iconBounce 2s ease-in-out infinite',
        'icon-glow': 'iconGlow 2.5s ease-in-out infinite',
        'sidebar-pulse': 'sidebarActivePulse 2s ease-in-out infinite',
        'float-slow': 'floatSlow 6s ease-in-out infinite',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite',
        'slide-down-fade': 'slideDownFade 0.3s ease-out forwards',
        'heartbeat': 'heartbeat 2.5s ease-in-out infinite',
        'heartbeat-line': 'heartbeatLine 3s linear infinite',
        'ai-sparkle': 'aiSparkle 3s ease-in-out infinite',
        'breathing-glow': 'breathingGlow 2.5s ease-in-out infinite',
        'page-enter': 'pageEnter 0.25s cubic-bezier(0.4,0,0.2,1) forwards',
        'fade-slide-up': 'fadeSlideUp 0.8s cubic-bezier(0.16,1,0.3,1) forwards',
        'counter-number': 'counterNumber 0.6s ease-out forwards',
        'ticker': 'ticker 30s linear infinite',
        'neural-pulse': 'neuralPulse 2s ease-in-out infinite',
        'voice-wave': 'voiceWave 0.8s ease-in-out infinite',
        'morph-blob': 'morphBlob 12s ease-in-out infinite',
        'role-gradient-flow': 'roleGradientFlow 28s cubic-bezier(0.45, 0.05, 0.55, 0.95) infinite',
        'pulse-ring': 'pulseRing 2s ease-out infinite',
        'progress-fill': 'progressFill 1.5s ease-out forwards',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeInUp: { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeInDown: { '0%': { opacity: '0', transform: 'translateY(-20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideInUp: { '0%': { transform: 'translateY(30px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        slideInLeft: { '0%': { transform: 'translateX(-30px)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        slideInRight: { '0%': { transform: 'translateX(30px)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        zoomIn: { '0%': { transform: 'scale(0.95)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        zoomOut: { '0%': { transform: 'scale(1.05)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        scaleIn: { '0%': { transform: 'scale(0.9)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        bounceIn: { '0%': { transform: 'scale(0.3)', opacity: '0' }, '50%': { transform: 'scale(1.05)' }, '70%': { transform: 'scale(0.9)' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        chartEntrance: { '0%': { opacity: '0', transform: 'scale(0.96) translateY(10px)' }, '100%': { opacity: '1', transform: 'scale(1) translateY(0)' } },
        countUp: { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        shimmer: { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(100%)' } },
        float: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
        borderGlow: { '0%, 100%': { borderColor: 'rgba(99, 102, 241, 0.3)', boxShadow: '0 0 5px rgba(99, 102, 241, 0.1)' }, '50%': { borderColor: 'rgba(99, 102, 241, 0.8)', boxShadow: '0 0 20px rgba(99, 102, 241, 0.3)' } },
        gradientShift: { '0%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' }, '100%': { backgroundPosition: '0% 50%' } },
        slideDown: { '0%': { maxHeight: '0', opacity: '0' }, '100%': { maxHeight: '500px', opacity: '1' } },
        slideUp: { '0%': { maxHeight: '500px', opacity: '1' }, '100%': { maxHeight: '0', opacity: '0' } },
        pop: { '0%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.15)' }, '100%': { transform: 'scale(1)' } },
        livePulse: { '0%, 100%': { opacity: '0.6', transform: 'scale(1)' }, '50%': { opacity: '1', transform: 'scale(1.05)' } },
        ripple: { '0%': { boxShadow: '0 0 0 0 rgba(59, 130, 246, 0.4)' }, '100%': { boxShadow: '0 0 0 15px rgba(59, 130, 246, 0)' } },
        shake: { '0%, 100%': { transform: 'translateX(0)' }, '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-4px)' }, '20%, 40%, 60%, 80%': { transform: 'translateX(4px)' } },
        dataFlash: { '0%': { backgroundColor: 'rgba(14, 165, 233, 0.15)' }, '100%': { backgroundColor: 'transparent' } },
        barRise: { '0%': { transform: 'scaleY(0)' }, '100%': { transform: 'scaleY(1)' } },
        subtlePulse: { '0%, 100%': { transform: 'scale(1)', boxShadow: '0 0 5px transparent' }, '50%': { transform: 'scale(1.03)', boxShadow: '0 0 25px rgba(14, 165, 233, 0.4)' } },
        iconBounce: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '25%': { transform: 'translateY(-3px) rotate(-2deg)' }, '75%': { transform: 'translateY(-1px) rotate(2deg)' } },
        iconGlow: { '0%, 100%': { filter: 'drop-shadow(0 0 2px currentColor)' }, '50%': { filter: 'drop-shadow(0 0 8px currentColor)' } },
        sidebarActivePulse: { '0%, 100%': { opacity: '0.6', transform: 'scale(1)' }, '50%': { opacity: '1', transform: 'scale(1.15)' } },
        floatSlow: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '33%': { transform: 'translateY(-3px) rotate(0.5deg)' }, '66%': { transform: 'translateY(2px) rotate(-0.5deg)' } },
        glowPulse: { '0%, 100%': { boxShadow: '0 0 5px rgba(37,99,235,0.2)' }, '50%': { boxShadow: '0 0 20px rgba(37,99,235,0.4), 0 0 40px rgba(37,99,235,0.1)' } },
        slideDownFade: { 'from': { opacity: '0', transform: 'translateY(-8px)' }, 'to': { opacity: '1', transform: 'translateY(0)' } },
        heartbeat: { '0%, 100%': { transform: 'scale(1)', boxShadow: '0 8px 24px rgba(37,99,235,0.25)' }, '14%': { transform: 'scale(1.08)', boxShadow: '0 8px 32px rgba(37,99,235,0.35)' }, '28%': { transform: 'scale(1)', boxShadow: '0 8px 24px rgba(37,99,235,0.25)' }, '42%': { transform: 'scale(1.05)', boxShadow: '0 8px 28px rgba(37,99,235,0.3)' }, '56%': { transform: 'scale(1)', boxShadow: '0 8px 24px rgba(37,99,235,0.25)' } },
        heartbeatLine: { '0%': { strokeDashoffset: '0' }, '100%': { strokeDashoffset: '-120' } },
        aiSparkle: { '0%, 100%': { opacity: '0.3', transform: 'scale(0.8) rotate(0deg)' }, '50%': { opacity: '1', transform: 'scale(1.2) rotate(180deg)' } },
        breathingGlow: { '0%, 100%': { boxShadow: '0 0 4px rgba(99,102,241,0.2)' }, '50%': { boxShadow: '0 0 16px rgba(99,102,241,0.4), 0 0 32px rgba(99,102,241,0.1)' } },
        pageEnter: { 'from': { opacity: '0', transform: 'translateY(8px)' }, 'to': { opacity: '1', transform: 'translateY(0)' } },
      },
      transitionProperty: {
        'height': 'height',
        'spacing': 'margin, padding',
        'transform-opacity': 'transform, opacity',
      },
      transitionDuration: {
        '250': '250ms',
        '400': '400ms',
        '600': '600ms',
        '800': '800ms',
      },
      transitionTimingFunction: {
        'bounce-in': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'spring': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      },
      colors: {
        glass: {
          light: 'rgba(255, 255, 255, 0.7)',
          DEFAULT: 'rgba(255, 255, 255, 0.8)',
          dark: 'rgba(255, 255, 255, 0.9)',
        },
        // Design system colors
        'lifelink': {
          blue: '#2563EB',
          'blue-dark': '#1D4ED8',
          purple: '#7C3AED',
          'purple-dark': '#6D28D9',
          emergency: '#DC2626',
          'emergency-dark': '#B91C1C',
          success: '#059669',
          'success-dark': '#047857',
          warning: '#F59E0B',
          'warning-dark': '#D97706',
        },
        'border-light': '#E5E7EB',
        'bg-soft': '#F9FAFB',
        'text-muted': '#6B7280',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
};
