"""Initial schema — represents the existing schema.sql state.

This is an empty migration because the actual schema is managed by
schema.sql / bootstrap_database.py. Alembic stamps this as the head
so future autogenerated migrations can build on top of it.

Revision ID: 0001
Revises: None
Create Date: 2026-07-20
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Base schema is applied by bootstrap_database.py via schema.sql
    # This migration is a marker so Alembic knows the starting point
    pass


def downgrade() -> None:
    pass
